language: generic
sudo: required
dist: bionic
addons:
  apt:
    packages:
      - ca-certificates
env:
  global:
    - secure: "GBRVgHZaHgt8Qof6WQ/3D0yX2nOa7h5vDTFy4ELbC7d2OT1zce5OscD8RBW5HufA+L+ITBoAyqdyNW6wdRdloaBMM/O/qp5bNXbpohzMe3D2Vn4Rm/HBOMYMvMeIxKxlguDurwrrnZdEMkwa9Yh63SEgtwnDIftSurCChI2FmVK38VNkIhjr50UOyPEIReI38DZtO56qIyv8YlH+4YTgHiGR1Id3ftPztUxxO59NKg7OuG1LOjz3JLmcNdH2Vh3DlYzGx5vm7rU6XCv0UqWu8zPCW9w5ITk6iT6FzGadpsaTnGR7IFChnEzlalfBa51Hrdf40ks9g38eGbtRUQ58qhuoKCjaBFXYEqgU+yydey5FWD3Yf9t8PM8KcNW1Dq23+pev0GdaZ73GrznR1yE5yUj4POkqiwEGLHpns6GjR/BKz5E+oUEdWgsX3/qOcvpnwdkoHQbNa8QkP/Ua4h37uJu8LMYijF71Jt+B6x/hCEMc+IsRhEkznXqoNzD241epA+49VuUl5Sp9XXp6XfbEuC6jH/rGbXeqv5394cZeBcN9jCY2B6FGVk4Wwff32v2GdmbK1UXXWyMv0xjN/IHXJpdGXqvaz8s6CyAMbHi9lp9mmLAuYKCCX+5SzTgRBgerHNESzA10kJrr7MrV2+5iVHeRyzLMctO0NCsIrUQ6NpI="
    - secure: "Zlpzek/XBqyuMUkQ0Gils1pBzmYjxjiTPRtKhTKNlS0ArzYKQJoj220V8r1DlxspBgBGQgaqyt4oBD0/OFyqYaQtS+OvzNp0BodB66lbPP65NhbrruszuR1AUaW0YkaoiFpTeDA4l/3SJAlJAL1xYBUYwzjm0sTvdUAu2u8iv1jHYy2nFv2iv/cOYqEA9Td3MqTbLKUeyCcimmCn1U8qF4VxLMSLjTVmjccxxEQwu9mmY7JCjGnzt3dMjBWn0pXolGEXXE/UtI2NtKweuNJzeIhPIEtxb/gQKSFf5JO0TLqFrrleTLz9oqYiYnTPL8TJaST2apOiKqq10ZLB09AmA+4rp46dxUj0o2JPd/2npthTHbEKbm/NB2XJR6k9gDJyREKllmZF+2+Co6Dc+vd2IjqvbbEGH10DAnj1JuCd4ZlC/dccmKjCWaxXBihOLDvzQsmfyuPapX+tun4fnSJqPPpjbhe2nni9A6qG9+CcuKtmC6nJKo7bKt209S+fzRZpwLF3M2FqtSyISdHRTrG5hI1LIFZkE5gkwF/t/lVaNuKNZ+MyO4hLmjxav5XWtWMuvHB61IXiLOz+SFksS7I/5/QIRuHepZlgI2k3Nh8zqd+a/xUs8ZBCXgdwOq7ygB7f7Plz1uNz6S17Aw72cbqlxP6KLJEDbRerArBznQRDdP8="
    - secure: "kO+8mSAmAWNItErAmVnVpQICg/RdXfXGD++VnlvQav7skW3vYeSKrYhXwJx+im1Nto7bKO54j5rl8aiZ2HdKOMVii8rS1hhjmaVevl4vL2RwpKB6Lr0vL3GkH/Zlxd2wIJvOr1/eqk1E/Pf8oL+Fr/YdVze0V/gPudEZId3wtzLSpnPF2CWI5g5rXPUKjMy25zSEJvFx49g7bfJX62xRn/DU7Wl2/Id/Mh0degqacgJmz82zoZ2lJm271t4GzWxMrCar+ZZYZg/zGPtYwPNOf2+h0NQ4PlrWdySiox8g1hYOt7u2o1Pc0OyzAuDExmDBGJ0YHQomu8bIJP5I+epwkiNT4uIjZEceeTBK+gbXZf7vFpTAaHRkqSbNRTsUrH9KkroK2bphu2m4ORj5dxc6tKChoRtfuNtokJ9VucocYWnIMm8+I488dcY0EaunRu9ARckXvQ1a6EsgcvM6Uni0BTZW2bWoyYLLi0DTmP3f4VZzAQtApztLEbk8+mQxruk7lbu5QO3aiVswwT41U9TvT5mfJfoGvV94HJbdpjf1R2oyqS+cPAPDA31dq/n+NA7wyZIS66ZRtC9wLIvi+QBzIfI74xQoGtN6UXmu3wb3g9fwgDXnAJDyLMA2COw38uDR84QeeKCZN9siAhCKROcrCCPzHudAMgF5pdf6V1ODaRQ="
jobs:
  fast_finish: true
  allow_failures:
    - os: windows
  include:
    - stage: motionless
      script: ./ci/travis_stage_script.sh motionless
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=motionless
      os: linux
    - stage: motionless
      script: ./ci/travis_stage_script.sh motionless
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=motionless
      os: linux
    - stage: salem
      script: ./ci/travis_stage_script.sh salem
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=salem
      os: linux
    - stage: salem
      script: ./ci/travis_stage_script.sh salem
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=salem
      os: linux
    - stage: pytest-mpl
      script: ./ci/travis_stage_script.sh pytest-mpl
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=pytest-mpl
      os: linux
    - stage: pytest-mpl
      script: ./ci/travis_stage_script.sh pytest-mpl
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=pytest-mpl
      os: linux
    - stage: oggm-deps
      script: ./ci/travis_stage_script.sh oggm-deps
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=oggm-deps
      os: linux
    - stage: oggm-deps
      script: ./ci/travis_stage_script.sh oggm-deps
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=oggm-deps
      os: linux
    - stage: oggm
      script: ./ci/travis_stage_script.sh oggm
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=oggm
      os: linux
    - stage: oggm
      script: ./ci/travis_stage_script.sh oggm
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=oggm
      os: linux
    - stage: oggm
      script: ./ci/travis_stage_script.sh oggmdev
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=oggmdev
      os: linux
    - stage: oggm
      script: ./ci/travis_stage_script.sh oggmdev
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=oggmdev
      os: linux
    - stage: make_env
      script: ./ci/appveyor_trigger_from_travis.sh
      env: CONDA_BUILD_PY=Trigger_Appveyor
      os: linux
    - stage: make_env
      script: ./ci/travis_make_env_script.sh
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=oggm
      os: linux
    - stage: make_env
      script: ./ci/travis_make_env_script.sh
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=oggm
      os: linux
    - stage: make_env
      script: ./ci/travis_make_env_script.sh
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=oggm
      os: osx
      osx_image: xcode11
    - stage: make_env
      script: ./ci/travis_make_env_script.sh
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=oggm
      os: osx
      osx_image: xcode11
    - stage: make_env
      script: ./ci/travis_make_env_script.sh
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=oggmdev
      os: linux
    - stage: make_env
      script: ./ci/travis_make_env_script.sh
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=oggmdev
      os: linux
    - stage: make_env
      script: ./ci/travis_make_env_script.sh
      env: CONDA_BUILD_PY=3.6 SUB_STAGE=oggmdev
      os: osx
      osx_image: xcode11
    - stage: make_env
      script: ./ci/travis_make_env_script.sh
      env: CONDA_BUILD_PY=3.7 SUB_STAGE=oggmdev
      os: osx
      osx_image: xcode11
