language: generic
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - ca-certificates
env:
  global:
    - secure: "GBRVgHZaHgt8Qof6WQ/3D0yX2nOa7h5vDTFy4ELbC7d2OT1zce5OscD8RBW5HufA+L+ITBoAyqdyNW6wdRdloaBMM/O/qp5bNXbpohzMe3D2Vn4Rm/HBOMYMvMeIxKxlguDurwrrnZdEMkwa9Yh63SEgtwnDIftSurCChI2FmVK38VNkIhjr50UOyPEIReI38DZtO56qIyv8YlH+4YTgHiGR1Id3ftPztUxxO59NKg7OuG1LOjz3JLmcNdH2Vh3DlYzGx5vm7rU6XCv0UqWu8zPCW9w5ITk6iT6FzGadpsaTnGR7IFChnEzlalfBa51Hrdf40ks9g38eGbtRUQ58qhuoKCjaBFXYEqgU+yydey5FWD3Yf9t8PM8KcNW1Dq23+pev0GdaZ73GrznR1yE5yUj4POkqiwEGLHpns6GjR/BKz5E+oUEdWgsX3/qOcvpnwdkoHQbNa8QkP/Ua4h37uJu8LMYijF71Jt+B6x/hCEMc+IsRhEkznXqoNzD241epA+49VuUl5Sp9XXp6XfbEuC6jH/rGbXeqv5394cZeBcN9jCY2B6FGVk4Wwff32v2GdmbK1UXXWyMv0xjN/IHXJpdGXqvaz8s6CyAMbHi9lp9mmLAuYKCCX+5SzTgRBgerHNESzA10kJrr7MrV2+5iVHeRyzLMctO0NCsIrUQ6NpI="

jobs:
  include:
    - stage: motionless
      script: travis_wait 60 ./ci/travis_stage_script.sh motionless
      env: CONDA_BUILD_PY=3.5
      os: linux
    - stage: motionless
      script: travis_wait 60 ./ci/travis_stage_script.sh motionless
      env: CONDA_BUILD_PY=3.6
      os: linux
    - stage: motionless
      script: travis_wait 60 ./ci/travis_stage_script.sh motionless
      env: CONDA_BUILD_PY=3.5
      os: osx
      osx_image: xcode9.1
    - stage: motionless
      script: travis_wait 60 ./ci/travis_stage_script.sh motionless
      env: CONDA_BUILD_PY=3.6
      os: osx
      osx_image: xcode9.1
    - stage: salem
      script: travis_wait 60 ./ci/travis_stage_script.sh salem
      env: CONDA_BUILD_PY=3.5
      os: linux
    - stage: salem
      script: travis_wait 60 ./ci/travis_stage_script.sh salem
      env: CONDA_BUILD_PY=3.6
      os: linux
    - stage: salem
      script: travis_wait 60 ./ci/travis_stage_script.sh salem
      env: CONDA_BUILD_PY=3.5
      os: osx
      osx_image: xcode9.1
    - stage: salem
      script: travis_wait 60 ./ci/travis_stage_script.sh salem
      env: CONDA_BUILD_PY=3.6
      os: osx
      osx_image: xcode9.1
    - stage: oggm-deps
      script: travis_wait 60 ./ci/travis_stage_script.sh oggm-deps
      env: CONDA_BUILD_PY=3.5
      os: linux
    - stage: oggm-deps
      script: travis_wait 60 ./ci/travis_stage_script.sh oggm-deps
      env: CONDA_BUILD_PY=3.6
      os: linux
    - stage: oggm-deps
      script: travis_wait 60 ./ci/travis_stage_script.sh oggm-deps
      env: CONDA_BUILD_PY=3.5
      os: osx
      osx_image: xcode9.1
    - stage: oggm-deps
      script: travis_wait 60 ./ci/travis_stage_script.sh oggm-deps
      env: CONDA_BUILD_PY=3.6
      os: osx
      osx_image: xcode9.1
    - stage: oggm
      script: travis_wait 60 ./ci/travis_stage_script.sh oggm
      env: CONDA_BUILD_PY=3.5
      os: linux
    - stage: oggm
      script: travis_wait 60 ./ci/travis_stage_script.sh oggm
      env: CONDA_BUILD_PY=3.6
      os: linux
    - stage: oggm
      script: travis_wait 60 ./ci/travis_stage_script.sh oggm
      env: CONDA_BUILD_PY=3.5
      os: osx
      osx_image: xcode9.1
    - stage: oggm
      script: travis_wait 60 ./ci/travis_stage_script.sh oggm
      env: CONDA_BUILD_PY=3.6
      os: osx
      osx_image: xcode9.1
